services:
  statping:
    container_name: statping
    # image: gitlab.socotec.io:4567/socotec.io/platform/fluxcd/statping-ng:v1.20
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    volumes:
      - statping_data:/app
      - ./services.yml:/app/services.yml
    depends_on:
      - postgres
    environment:
      DB_CONN: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: statping
      DB_USER: statpingng
      DB_PASS: g6CUtKX3WB9yuwTw
      DEBUG: "1"
      LANGUAGE: "french"
      NAME: "Socotec.io status page"
      ADMIN_USER: admin
      ADMIN_PASSWORD: password
      READ_ONLY: "false"
      DISABLE_COLORS: "false"
      DOMAIN: http://localhost:8080
      PORT: 8080
      SAMPLE_DATA: "false"
      API_SECRET: CGXXBs0QlZXhS4YSL7C5
      NOTION_API_KEY: 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
      NOTION_DATABASE_ID: 157ac16e3d028120b7e7d4c174efe193
      STATPING_API_KEY: CGXXBs0QlZXhS4YSL7C5
      STATPING_DOMAIN: localhost
      STATPING_URL: http://statping-ng.statping-ng.svc.cluster.local:8080
      TEAMS_WEBHOOK_URL: https://socotecgroup.webhook.office.com/webhookb2/2d463e72-62aa-435d-81d7-32dfc3f0cf3d@33135fa5-f5a7-4d5c-8632-9a17d4acfa5b/IncomingWebhook/a187effc8f0c476fb545cdd4369eb16b/e5c2c37c-07be-45eb-aab6-fb8c595e64c7/V2fbzi61KuotSKI9XT8zmFStFuKxYv9lz8z71zd2A7B_o1
      KEYCLOAK_CLIENT_ID: statping-ng
      KEYCLOAK_CLIENT_SECRET: Yky9lOP7teqcRxuUKSdF89yI9DFwnv0v
      KEYCLOAK_ENDPOINT_AUTH: "https://sso.development.infra-socotec.net/auth/realms/socotec-user/protocol/openid-connect/auth"
      KEYCLOAK_ENDPOINT_TOKEN: "https://sso.development.infra-socotec.net/auth/realms/socotec-user/protocol/openid-connect/token"
      KEYCLOAK_ENDPOINT_USERINFO: "https://sso.development.infra-socotec.net/auth/realms/socotec-user/protocol/openid-connect/userinfo"
      KEYCLOAK_SCOPES: openid,profile,email
      KEYCLOAK_IS_OPEN_ID: "true"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  postgres:
    container_name: postgres
    image: postgres:14.15-alpine
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/pg_data
    environment:
      POSTGRES_PASSWORD: g6CUtKX3WB9yuwTw
      POSTGRES_DB: statping
      POSTGRES_USER: statpingng
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/pg_data
    networks:
      - app_network

volumes:
  statping_data:
  pg_data:

networks:
  app_network:
    external: true
    name: statping_network